# Generated by Django 4.2.2 on 2023-09-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_publish', models.CharField(auto_created=True)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('writer', models.CharField(max_length=250)),
            ],
        ),
    ]
